DROP DATABASE IF EXISTS stocksDB;

CREATE DATABASE stocksDB;

USE stocksDB;
CREATE TABLE IF NOT EXISTS users (
  id MEDIUMINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(40) UNIQUE,
  password TEXT,
  cash FLOAT DEFAULT 1000
);

CREATE TABLE IF NOT EXISTS stocks(
  id MEDIUMINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  symbol TEXT,
  name TEXT,
  shares INT,
  price FLOAT,
  total FLOAT,
  user_id MEDIUMINT,
  CONSTRAINT FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS history(
  id MEDIUMINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id MEDIUMINT,
  CONSTRAINT FOREIGN KEY (user_id) REFERENCES users(id),
  symbol TEXT,
  name TEXT,
  price FLOAT,
  share INT,
  total FLOAT,
  createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);