DROP DATABASE IF EXISTS stocks;

CREATE DATABASE stocks;

USE stocks;
CREATE TABLE IF NOT EXISTS users (
  id MEDIUMINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(40) UNIQUE,
  password VARCHAR(64),
  salt VARCHAR(64),
  cash FLOAT NOT NULL DEFAULT 100
);

CREATE TABLE IF NOT EXISTS stocks(
  id MEDIUMINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  symbol TEXT,
  name TEXT,
  shares INT,
  price FLOAT,
  total FLOAT,
  user_id MEDIUMINT,
  CONSTRAINT FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS history(
  id MEDIUMINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  stock_id MEDIUMINT,
  CONSTRAINT FOREIGN KEY (stock_id) REFERENCES stocks(id),
  price FLOAT,
  share INT,
  total FLOAT,
  createAt TIMESTAMP
);